### ISSUE TITLE
Viewer program

### ISSUE THREAD

**Issue by alexreg** [slog-rs/json#1]
I could see this becoming the de-facto standard logging format for Slog, if a viewer program were to be provided alongside it. Perhaps one that simply reads from the JSON format, and outputs in the slog-term format, with some basic searching and date-time range capabilities. Is this in your plans?

**Comment by dpc** [comment]
I had no plans like this. JSON is so ubiquitous that there are multitude of tools to handle them. A viewing software would be potentially more work to write and maintain than slog itself.

If you do find something working for you, or plan to work on it, please let us know!

**Comment by alexreg** [comment]
Okay, but there's the general JSON format, then the specific structure of Slog JSON log files... I think I may write a viewing tool myself. We'll see.

**Comment by dpc** [comment]
`slog-json` does not really define anything that goes into the json. It's entirely up to the user to define time format, logging severyty key and format and so on. There are some defaults, but they are mostly for users that don't really care. `bunyan` on the other hand is JSON + definition of key-values semantics.

**Comment by alexreg** [comment]
So it’s just a thin wrapper over *slog-stream* really? I didn’t know that (had never actually used it, only judged from what you said about it). Fair enough!

**Comment by dpc** [comment]
`slog-stream` provides a `Drain` that takes something implementing `Format` and writes it to something implementing `io::Writer`.

`slog-json` uses `serde`  `serde-json`) and uses it to implement `Format` for `slog-stream` with additional fields (key + value) given by user.
