### ISSUE TITLE
Make it easier to log inline JSON with the "nested-values" feature

### ISSUE THREAD

**Issue by ncalexan** [slog-rs/json#19]
It surprised me that I couldn't log, say, a `Vec<i64>` _inline_ into `slog-json` easily, i.e., as a field
```
'nested-value': [0, 1, ...]
```
It turns out that this is possible, but it's not obvious how to do so, and there seem to be lots of conflicting information and questions about how to do this on the web (several threads in gitter, for example).  I made https://github.com/ncalexan/slog-nested-values-example to work out what I needed to do to achieve this, so I'll just drop that link here for the next person trying to work this out.  But I have two requests:

1.  Can we expose the obvious `SerdeValueWrapper<T>` (with a JSON string as fallback?) as part of this crate?  (Or `slog-rs` itself, I guess.)  There's not much sense having everybody discover the incantations themselves.  I imagine that the loss of flexibility is real, but can we support both paths?
2.  Can we add examples and tests of this functionality, 'cuz it's not obvious that it exists without that?  There's not much sense not capturing this useful functionality.

Thoughts?

**Comment by dpc** [comment]
I'm happy to add useful things into main `slog` crate as long as they are not introducing more dependencies. There's always a route of making `slog-serde` and mentioning it in a couple of places in the documentation of `slog` itself.

**Comment by dcormier** [comment]
What about adding it to [the existing `slog-serde` crate](https://github.com/slog-rs/serde)?

**Comment by dcormier** [comment]
Or, alternatively, do what many crates seem to do and add a non-default `serde` feature where the dependency is only added if it's enabled? This feature would simply add `impl slog::Value for T` and `slog::SerdeValue for T` where `T: serde::Serialize`. This way, users would be able to have their values written to JSON without having to go through extra hoops of wrapping them with another struct each time.

Would this be acceptable?

**Comment by dpc** [comment]
Isn't that kind of already the case? https://github.com/slog-rs/slog/blob/f9e30f0dd9bad610227d9374001fcc13d5b7c8c8/Cargo.toml#L30

**Comment by dpc** [comment]
`slog::SerdeValue for T where T: serde::Serialize` would be a trait implementation conflict
