### ISSUE TITLE
Enhancement: Pretty-printed JSON output

### ISSUE THREAD

**Issue by brennie** [slog-rs/json#9]
It would be nice for development if I could conditionally enable pretty-printed JSON output.

**Comment by dpc** [comment]
It would be! Please submit PR! :) Just add a method to `JsonBuilder` and set the right mode. Feel free to ask for help on gitter.

**Comment by brennie** [comment]
I already gave it two attempts:


Store a `pretty` flag on the `Json` and `JsonBuilder` types and add a set `set_pretty` method to the builder. Unfortunately, `Json::ser::Serializer` is parameterized by type so you can't do, e.g.


```rust
let serializer = if pretty { serde_json::ser::Serializer::new() } else {  serde_json::ser::Serializer::pretty() };
```
as the if statement's arms will have different types.

My second attempt involved adding a `set_formatter` function on the builder, and storing the formatter as `Box<serde_json::ser::Formatter>` but Formatter can not be instantiated to a type so I couldn't get it to work.

I'm quite new to Rust so I don't know that I know how to solve my second attempt. I suppose the first attempt could refactor the actual formatting into a function parameterized by a `Serializer` and do something like:

```rust
 if self.pretty {
    self.serialize_impl(json::pretty(...), ...)
} else {
    self.serialize_impl(json::new(...), ...)
}
```

I can take a look at doing this tomorrow and if I can get it working I'll submit a PR.

Thanks for being open to contribution!

**Comment by dpc** [comment]
If you have two types `T1` and `T2` both implementing same trait (`Trait`)and you want to use them interchangebly, you have to unify them to a common trait object. Typically it means boxing to `Box<Trait>`.

Feel free to reach out for help on `slog` gitter channel or https://www.rust-lang.org/en-US/community.html "#rust-beginners, an IRC channel". Rust community is really friendly, and we all try to keep it this way. Getting more proficient with Rust is much easier with some help.

**Comment by brennie** [comment]
FWIW the issue I was running into wasn't solved by `Box`. You can't have a `Box<serde_json::ser::Formatter>` I think because it is `?Sized`. The [erased-serde](https://github.com/dtolnay/erased-serde) crate does a workaround for serde but I didn't want to do all that boilerplate for `Formatter`

**Comment by dpc** [comment]
@brennie What's the problem with Box and `?Sized`. Box can explicitily store unsied types. That's part of what it's doing. See signature https://doc.rust-lang.org/std/boxed/struct.Box.html
